#ifndef TABLE_H
#define TABLE_H

#include <vector>
#include <stdint.h>

#include "instructions.h"

typedef void(*instr_ptr)();

struct instr_str{
    instr_ptr ptr;
    const char *name;
    uint8_t bytes;
    uint8_t cycles;
};

std::vector<instr_str> instr_table{
    { &NOP,             "NOP",              1,      4    },
    { &LD_BC_U16,       "LD BC, u16",       3,      12   },
    { &LD_ADDR_BC_A,    "LD (BC), A",       1,      8    },
    { &INC_BC,          "INC BC",           1,      8    },
    { &INC_B,           "INC B",            1,      4    },
    { &DEC_B,           "DEC B",            1,      4    },
    { &LD_B_U8,         "LD B, u8",         2,      8    },
    { &RLCA,            "RLCA",             1,      4    },
    { &LD_ADDR_U16_SP,  "LD (u16), SP",     3,      20   },
    { &ADD_HL_BC,       "ADD HL,BC",        1,      8    },
    { &LD_A_ADDR_BC,    "LD A, (BC)",       1,      8    },
    { &DEC_BC,          "DEC BC",           1,      8    },
    { &INC_C,           "INC C",            1,      4    },
    { &DEC_C,           "DEC C",            1,      4    },
    { &LD_C_U8,         "LD C, u8",         2,      8    },
    { &RRCA,            "RRCA",             1,      4    },
    { &STOP,            "STOP",             1,      4    },
    { &LD_DE_U16,       "LD DE, u16",       3,      12   },
    { &LD_ADDR_DE_A,    "LD (DE), A",       1,      8    },
    { &INC_DE,          "INC DE",           1,      8    },
    { &INC_D,           "INC D",            1,      4    },
    { &DEC_D,           "DEC D",            1,      4    },
    { &LD_D_U8,         "LD D, u8",         2,      8    },
    { &RLA,             "RLA",              1,      4    },
    { &JR_I8,           "JR i8",            2,      12   },
    { &ADD_HL_DE,       "ADD HL,DE",        1,      8    },
    { &LD_A_ADDR_DE,    "LD A, (DE)",       1,      8    },
    { &DEC_DE,          "DEC DE",           1,      8    },
    { &INC_E,           "INC E",            1,      4    },
    { &DEC_E,           "DEC E",            1,      4    },
    { &LD_E_U8,         "LD E, u8",         1,      8    },
    { &RRA,             "RRA",              1,      4    },
    { &JR_NZ_I8,        "JR NZ, i8",        2,      8+12 },
    { &LD_HL_U16,       "LD HL, u16",       3,      12   },
    { &LD_ADDR_HLp_A,   "LD (HL+), A",      1,      8    },
    { &INC_HL,          "INC HL",           1,      8    },
    { &INC_H,           "INC H",            1,      4    },
    { &DEC_H,           "DEC H",            1,      4    },
    { &LD_H_U8,         "LD H, u8",         2,      8    },
    { &DAA,             "DAA",              1,      4    },
    { &JR_Z_I8,         "JR Z, i8",         2,      8+12 },
    { &ADD_HL_HL,       "ADD HL, HL",       1,      8    },
    { &LD_A_ADDR_HLp,   "LD A, (HL+)",      1,      8    },
    { &DEC_HL,          "DEC HL",           1,      8    },
    { &INC_L,           "INC L",            1,      4    },
    { &DEC_L,           "DEC L",            1,      4    },
    { &LD_L_U8,         "LD L, u8",         2,      8    },
    { &CPL,             "CPL",              1,      4    },
    { &JR_NC_I8,        "JR NC, i8",        2,      8+12 },
    { &LD_SP_U16,       "LD SP, u16",       3,      12   },
    { &LD_ADDR_HLm_A,   "LD (HL-), A",      1,      8    },
    { &INC_SP,          "INC SP",           1,      8    },
    { &INC_ADDR_HL,     "INC (HL)",         1,      12   },
    { &DEC_ADDR_HL,     "DEC (HL)",         1,      12   },
    { &LD_ADDR_HL_U8,   "LD (HL), u8",      2,      12   },
    { &SCF,             "SCF",              1,      4    },
    { &JR_C_I8,         "JR C, i8",         2,      8+12 },
    { &ADD_HL_SP,       "ADD HL, SP",       1,      8    },
    { &LD_A_ADDR_HLm,   "LD A, (HL-)",      1,      8    },
    { &DEC_SP,          "DEC SP",           1,      8    },
    { &INC_A,           "INC A",            1,      4    },
    { &DEC_A,           "DEC A",            1,      4    },
    { &LD_A_U8,         "LD A, u8",         2,      8    },
    { &CCF,             "CCF",              1,      4    },
    { &LD_B_B,          "LD B, B",          1,      4    },
    { &LD_B_C,          "LD B, C",          1,      4    },
    { &LD_B_D,          "LD B, D",          1,      4    },
    { &LD_B_E,          "LD B, E",          1,      4    },
    { &LD_B_H,          "LD B, H",          1,      4    },
    { &LD_B_L,          "LD B, L",          1,      4    },
    { &LD_B_ADDR_HL,    "LD B, (HL)",       1,      8    },
    { &LD_B_A,          "LD B, A",          1,      4    },
    { &LD_C_B,          "LD C, B",          1,      4    },
    { &LD_C_C,          "LD C, C",          1,      4    },
    { &LD_C_D,          "LD C, D",          1,      4    },
    { &LD_C_E,          "LD C, E",          1,      4    },
    { &LD_C_H,          "LD C, H",          1,      4    },
    { &LD_C_L,          "LD C, L",          1,      4    },
    { &LD_C_ADDR_HL,    "LD C, (HL)",       1,      8    },
    { &LD_C_A,          "LD C, A",          1,      4    },
    { &LD_D_B,          "LD D, B",          1,      4    },
    { &LD_D_C,          "LD D, C",          1,      4    },
    { &LD_D_D,          "LD D, D",          1,      4    },
    { &LD_D_E,          "LD D, E",          1,      4    },
    { &LD_D_H,          "LD D, H",          1,      4    },
    { &LD_D_L,          "LD D, L",          1,      4    },
    { &LD_D_ADDR_HL,    "LD D, (HL)",       1,      8    },
    { &LD_D_A,          "LD D, A",          1,      4    },
    { &LD_E_B,          "LD E, B",          1,      4    },
    { &LD_E_C,          "LD E, C",          1,      4    },
    { &LD_E_D,          "LD E, D",          1,      4    },
    { &LD_E_E,          "LD E, E",          1,      4    },
    { &LD_E_H,          "LD E, H",          1,      4    },
    { &LD_E_L,          "LD E, L",          1,      4    },
    { &LD_E_ADDR_HL,    "LD E, (HL)",       1,      8    },
    { &LD_E_A,          "LD E, A",          1,      4    },
    { &LD_H_B,          "LD H, B",          1,      4    },
    { &LD_H_C,          "LD H, C",          1,      4    },
    { &LD_H_D,          "LD H, D",          1,      4    },
    { &LD_H_E,          "LD H, E",          1,      4    },
    { &LD_H_H,          "LD H, H",          1,      4    },
    { &LD_H_L,          "LD H, L",          1,      4    },
    { &LD_H_ADDR_HL,    "LD H, (HL)",       1,      8    },
    { &LD_H_A,          "LD H, A",          1,      4    },
    { &LD_L_B,          "LD L, B",          1,      4    },
    { &LD_L_C,          "LD L, C",          1,      4    },
    { &LD_L_D,          "LD L, D",          1,      4    },
    { &LD_L_E,          "LD L, E",          1,      4    },
    { &LD_L_H,          "LD L, H",          1,      4    },
    { &LD_L_L,          "LD L, L",          1,      4    },
    { &LD_L_ADDR_HL,    "LD L, (HL)",       1,      8    },
    { &LD_L_A,          "LD L, A",          1,      4    },
    { &LD_ADDR_HL_B,    "LD (HL), B",       1,      4    },
    { &LD_ADDR_HL_C,    "LD (HL), C",       1,      4    },
    { &LD_ADDR_HL_D,    "LD (HL), D",       1,      4    },
    { &LD_ADDR_HL_E,    "LD (HL), E",       1,      4    },
    { &LD_ADDR_HL_H,    "LD (HL), H",       1,      4    },
    { &LD_ADDR_HL_L,    "LD (HL), L",       1,      4    },
    { &HALT,            "HALT",             1,      4    },
    { &LD_ADDR_HL_A,    "LD (HL), A",       1,      4    },
    { &LD_A_B,          "LD A, B",          1,      4    },
    { &LD_A_C,          "LD A, C",          1,      4    },
    { &LD_A_D,          "LD A, D",          1,      4    },
    { &LD_A_E,          "LD A, E",          1,      4    },
    { &LD_A_H,          "LD A, H",          1,      4    },
    { &LD_A_L,          "LD A, L",          1,      4    },
    { &LD_A_ADDR_HL,    "LD A, (HL)",       1,      8    },
    { &LD_A_A,          "LD A, A",          1,      4    },
}

#endif